### ISSUE TITLE
Support for coc-references, by any chance?

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [neoclide/coc-denite#11]
It'd be great to be able to replace the :CocList interface for the last big thing I use it for — references.

For example, in a JavaScript file with `tsserver`, I can use `gr` to open a list of references to that value; but it unfortunately uses the `coc-list` mechanism; I'd much prefer to use the Coc.nvim data to populate a Denite interface.

Consider this a feature-request, if you've ever got the time! <3

**Comment by chemzqm** [comment]
It's possible, read doc of coc.nvim

**Comment by ELLIOTTCABLE** [comment]
I've … I read it a couple of times! I guess I'm missing something?

I see no mention of Denite in the documentation of coc.nvim.

**Comment by chemzqm** [comment]
checkout CocLocationsChange autocmd
